name: CI

on: [push]

jobs:
  build-nano:
    runs-on: ubuntu-latest
    name: Build Nano Edition
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Nano ISO
        run: make nano
      - name: Smoke test Nano ISO
        run: make smoke-nano
      - name: Upload Nano artifact
        uses: actions/upload-artifact@v4
        with:
          name: AFClone-Nano
          path: out/nano/*.iso

  build-standard:
    runs-on: ubuntu-latest
    name: Build Standard Edition
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Standard ISO
        run: make standard
      - name: Smoke test Standard ISO
        run: make smoke-standard
      - name: Upload Standard artifact
        uses: actions/upload-artifact@v4
        with:
          name: AFClone-Standard
          path: out/standard/*.iso
